 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    #dotnet buildd
     steps:
       - checkout
       - run:
          name: Testing application
          command: dotnet buildd
          working_directory: ~/TestLo
